# Generated by Django 5.0.2 on 2024-02-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_sondage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondage',
            name='creator',
        ),
    ]
