# Generated by Django 5.0.2 on 2024-02-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_sondage_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='created_by',
            field=models.EmailField(max_length=254),
        ),
    ]
