# Generated by Django 5.0.2 on 2024-02-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_sondage_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondage',
            name='created_by',
        ),
    ]
