# Generated by Django 5.0.2 on 2024-02-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='selected_options',
            new_name='choix',
        ),
    ]
