# Generated by Django 5.0.2 on 2024-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_answer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choix',
            field=models.CharField(max_length=50),
        ),
    ]
