# Generated by Django 5.0.2 on 2024-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_sondage_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
